# Generated by Django 2.2.10 on 2020-02-06 12:32

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200206_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='http://localhost:8000/media/', collection='media'), upload_to='media'),
        ),
    ]
