# Generated by Django 2.2.10 on 2020-02-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200206_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='ownwer',
        ),
    ]
