# Generated by Django 2.2.10 on 2020-02-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_author_ownwer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ownwer',
        ),
    ]
