# Generated by Django 2.2.10 on 2020-02-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_remove_book_ownwer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ownwer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(storage=djongo.storage.GridFSStorage(base_url='/media/', collection='media'), upload_to=''),
        ),
    ]
